#!/bin/sh
# tag tree, generate ChangeLog and roll a release tarball

set -e

self="$(basename "$0")"

usage() {
    echo "Usage: $self <version>"
}

log() {
    echo "$*" >&2
}

log_i() {
    log "I:" "$@"
}

die() {
    log "E:" "$@"
    exit 1
}

version="$1"

if [ -z "$version" ]; then
    usage >&2
    exit 1
fi

log_i "Checking tree status"
status=`bzr status`
if [ -n "$status" ]; then
    die "Tree is dirty according to bzr status"
fi

log_i "Running tests"
if ! python -m testtools.run linaro_image_tools.tests.test_suite; then
    die "Testsuite doesn't pass"
fi

log_i "Removing test repository data"
rm -rf .testrepository/

if bzr tags | awk '{print $1}' | grep -qFx "$version"; then
    die "Tag $version already exists"
fi

log_i "Setting version to $version in __version__.py"
sed -i "s/^\\(__version__\ =\ \"\\)[^\"]*\"\$/\1$version\"/" linaro_image_tools/__version__.py

log_i "Committing $version"
bzr commit -m "Release $version"

log_i "Creating tag $version"
bzr tag "$version"

log_i "Generating ChangeLog"
bzr log -v --gnu-changelog >ChangeLog

log_i "Creating release tarball in parent directory"
./setup.py sdist -d ..

log_i "Cleaning up"
rm -f ChangeLog MANIFEST

log_i "Signing tarball"
gpg --armor --sign --detach-sig "../linaro-image-tools-$version.tar.gz"

log_i "Setting version to $version (devel) in __version__.py"
sed -i "s/^\\(__version__\ =\ \"\\)[^\"]*\"\$/\1$version.1 (devel)\"/" linaro_image_tools/__version__.py

log_i "Committing $version.1 (devel)"
bzr commit -m "Post-release version bump to $version.1 (devel)"
