#! /bin/sh 

# do heavy copy of rootfs to destination
  echo "rsync rootfs Partition"

# parse params which must be in the order of
# ROOT_DISK DIR MMC2

  ROOT_DISK=$1
  DIR=$2
  MMC2=$3

  mkdir -p ${ROOT_DISK}
  sudo mount ${MMC2} ${ROOT_DISK}
  rsync -a ${DIR}/binary/etc ${DIR}/binary/usr ${DIR}/binary/lib ${DIR}/binary/bin ${DIR}/binary/home ${DIR}/binary/root ${DIR}/binary/media ${DIR}/binary/opt ${DIR}/binary/sbin ${DIR}/binary/var/backups  ${DIR}/binary/var/lib ${DIR}/binary/var/local  ${DIR}/binary/var/log  ${DIR}/binary/var/mail  ${DIR}/binary/var/opt  ${DIR}/binary/var/run  ${DIR}/binary/var/spool ${ROOT_DISK} 
  sudo umount ${ROOT_DISK} || true
